import type { Metadata } from 'next';
import { Geist, Geist_Mono, Francois_One } from 'next/font/google';

import '@repo/ui/globals.css';
import Provider from '@/providers/Provider';

const francoisOne = Francois_One({
  variable: '--font-francois',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${francoisOne.variable} ${francoisOne.className} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
