name: Continuous Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Linting
        run: bun run lint

      - name: Check types
        run: bun run check-types

      - name: Formatting
        run: bun run format

      - name: Remove dead imports
        run: bun run knip --no-exit-code

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Auditing packages
        run: bun audit

      - name: Secret Scan
        uses: advanced-security/secret-scanning-review-action@v1
        env:
          SECRET_TOKEN: ${{secrets.SECRET_TOKEN}}

  build:
    runs-on: ubuntu-latest
    needs:
      - quality
      - security
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Project Build
        run: bun run build
