name: Continuous Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Linting
        run: bun run lint

      - name: Check types
        run: bun run check-types

      - name: Formatting
        run: bun run format

      - name: Remove dead imports
        run: bun run knip --no-exit-code

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Auditing packages
        run: bun audit

      - name: Secret Scan
        uses: advanced-security/secret-scanning-review-action@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
        if: github.event_name == 'pull_request'

  build:
    runs-on: ubuntu-latest
    needs:
      - quality
      - security
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Installing Dependencies
        run: bun install

      - name: Project Build
        run: bun run build
        env:
          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: ${{ vars.BETTER_AUTH_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GITHUB_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
